repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0  
    hooks:
      - id: stylua  
        args: [--verify]  
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.1.0
    hooks:
      - id: luacheck  
        args: [--config=.luacheckrc]  